name: dstatus
version: git
summary: HUD for FIRST robotics build paces
description: Fill this out later
base: core18
confinement: devmode
grade: devel

parts:
  dstatus:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

  mesa:
    plugin: nil
    stage-packages:
      - libgl1
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa


apps:
  dstatus:
    command: "usr/bin/python3 -m dstatus --platform wayland"
